[workspace]
resolver = "2"
members = [
    "crates/clipx-core",
    "crates/clipx-store",
    "crates/clipx-monitor",
    "crates/clipx-ocr",
    "crates/clipx-everything",
    "crates/clipx-filejump",
    "crates/clipx-jump",
    "crates/clipx-app",
]

[workspace.package]
version = "0.5.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
clipx-core = { path = "crates/clipx-core" }
clipx-store = { path = "crates/clipx-store" }
clipx-monitor = { path = "crates/clipx-monitor" }
clipx-ocr = { path = "crates/clipx-ocr" }
clipx-everything = { path = "crates/clipx-everything" }
clipx-filejump = { path = "crates/clipx-filejump" }

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
