[package]
name = "clipx-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "clipx"
path = "src/main.rs"

[dependencies]
clipx-core = { workspace = true }
clipx-store = { workspace = true }
clipx-monitor = { workspace = true }
clipx-ocr = { workspace = true }
clipx-everything = { workspace = true }
clipx-filejump = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"] }
anyhow = { workspace = true }
slint = { version = "1", default-features = false, features = [
    "std",
    "backend-winit",
    "renderer-software",
    "compat-1-2",
    "accessibility",
    "raw-window-handle-06",
    "system-tray",
] }
raw-window-handle = "0.6"
clipboard-rs = "0.3.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
windows = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Console",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_System_Com",
    "Win32_System_DataExchange",
    "Win32_System_Ole",
    "Win32_System_Variant",
    "Win32_UI_Accessibility",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Input_Ime",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_Graphics_Gdi",
] }
global-hotkey = "0.8.0"

[build-dependencies]
slint-build = "1"
